repos:
- repo: https://github.com/nametake/pre-commit-buf
  rev: v2.0.0
  hooks:
  - id: buf-lint
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.32.0
  hooks:
  - id: yamllint
    args: [-c=.yamllint.yaml]
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.5.0
  hooks:
  - id: commitlint
    stages: [commit-msg]
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
# Do not enable this check until it can be run locally easily
# See: https://github.com/substrait-io/substrait/issues/771
# - repo: local
#   hooks:
#   - id: check-substrait-extensions_coverage
#     name: Check Substrait extensions and test coverage
#     entry: pytest tests/test_extensions.py::test_substrait_extension_coverage
#     language: python
#     pass_filenames: false
